### ISSUE TITLE
run failed maybe caused by environment variable

### ISSUE THREAD

**Issue by jaxsong** [danihodovic/celery-exporter#165]
Is there some special environment variable caused run failed with reason
```
2022-10-11 09:09:28.632 | ERROR    | src.exporter:run:255 - celery-exporter exception '[Errno 2] No such file or directory: '/home/app/gauge_all_1.db'', retrying in 0 seconds.
```

here is my run config
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-exporter
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-exporter
  template:
    metadata:
      labels:
        app: celery-exporter
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: celery-exporter
        image: danihodovic/celery-exporter:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9808
            name: metrics
            protocol: TCP
        args: ["--broker-url=redis://zeno-redis:6379/0"]
        envFrom:
          - configMapRef:
              name: my-config-map
        resources:
          requests:
            memory: 400Mi
          limits:
            memory: 800Mi

```

after I removed field `envFrom` , it worked
